<?php
/**
 * Redux Settings
 *
 * @package NaveinTheme
 * @version 1.0.0
 */
// Exit if accessed directly
defined( 'ABSPATH' ) || exit;

Redux::set_section(
	$opt_name,
	array(
		'title'      => esc_html__( 'Blog Typography', 'navein' ),
		'id'         => 'navein_blog_typography_settings',
        'icon'       => 'dashicons dashicons-arrow-right-alt',
		'subsection' => true,
		'fields'     => array(

            array(
				'id'    => 'navein_info_archive_posts_typo',
				'type'  => 'info',
                'title' => esc_html__( 'For Posts on - Blog Main Page / Archives Pages', 'navein' ),
			),
            array(
				'id'                => 'navein_archive_post_title_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Post Title', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-archive-post-title, .dtr-archive-post-title a' ),
			),
            array(
				'id'                => 'navein_archive_meta_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Meta', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
                'color'             => false,
				'output'            => array( '.dtr-entry-meta, .wp-block-latest-posts__post-author, .wp-block-latest-posts__post-date' ),
			),
            array(
				'id'          => 'navein_archive_meta_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Meta: Color', 'navein' ),
				'default'     => '',
				'transparent' => true,
				'validate'    => 'color',
				'output'      => array(
					'color' => '.dtr-entry-meta, .dtr-entry-meta a, .wp-block-latest-posts__post-author, .wp-block-latest-posts__post-date',
				),
			),
            array(
				'id'          => 'navein_archive_meta_icon_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Meta Icon: Color', 'navein' ),
				'default'     => '',
				'transparent' => true,
				'validate'    => 'color',
				'output'      => array(
					'color' => '.dtr-entry-meta .dtr-meta-item::before',
				),
			),
            array(
				'id'          => 'navein_archive_meta_hover_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Meta: Hover Color', 'navein' ),
				'default'     => '',
				'transparent' => true,
				'validate'    => 'color',
				'output'      => array(
					'color' => '.dtr-entry-meta a:hover',
				),
			),
			
            array(
				'id'    => 'navein_info_single_post_typo',
				'type'  => 'info',
                'title' => esc_html__( 'For : Single Post', 'navein' ),
			),
            array(
				'id'                => 'navein_single_post_title_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Post Title', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-single-post-title.dtr-page-title' ),
			),
            array(
				'id'                => 'navein_single_meta_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Meta', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
                'color'             => false,
				'output'            => array( '.dtr-single-meta' ),
			),
            array(
				'id'          => 'navein_single_meta_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Meta: Color', 'navein' ),
				'default'     => '',
				'transparent' => true,
				'validate'    => 'color',
				'output'      => array(
					'color' => '.dtr-single-meta, .dtr-single-meta .dtr-meta-item a',
				),
			),
            array(
				'id'          => 'navein_single_meta_icon_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Meta Icon: Color', 'navein' ),
				'default'     => '',
				'transparent' => true,
				'validate'    => 'color',
				'output'      => array(
					'color' => '.dtr-single-meta .dtr-meta-item::before',
				),
			),
            array(
				'id'          => 'navein_single_meta_hover_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Meta: Hover Color', 'navein' ),
				'default'     => '',
				'transparent' => true,
				'validate'    => 'color',
				'output'      => array(
					'color' => '.dtr-single-meta .dtr-meta-item a:hover',
				),
			),			
            array(
				'id'    => 'navein_info_sm_post_title',
				'type'  => 'info',
                'title' => esc_html__( 'Single Post Title - Sizes For Small Screens', 'navein' ),
				'desc'  =>  wp_kses( __('Set only if required', 'navein'), array( 'br' => array(), 'strong' => array(), ) ),
			),
            array(
				'id'       => 'navein_sm_post_title_size',
				'type'     => 'text',
				'title'    => esc_html__( 'Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_sm_post_title_lh',
				'type'     => 'text',
				'title'    => esc_html__( 'Line Height', 'navein' ),
				'default'  => '',
			),
            array(
				'id'    => 'navein_info_single_meta_title',
				'type'  => 'info',
                'title' => esc_html__( 'All Meta titles', 'navein' ),
                'subtitle' => esc_html__( 'This will work for titles to meta - date (e.g.published on), author (e.g. article by), tags and share', 'navein' ),
			),
            array(
				'id'                => 'navein_single_meta_title_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Font Settings', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-meta-title' ),
			),
            array(
				'id'    => 'navein_info_comment_section',
				'type'  => 'info',
                'title' => esc_html__( 'Comment Section', 'navein' ),
			),
            array(
				'id'                => 'navein_blog_comment_heading_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Comment Section Title', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.comments-title, .comment-reply-title' ),
			),
            array(
				'id'          => 'navein_blog_cancel_reply_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Cancel Reply Color', 'navein' ),
				'default'     => '',
				'transparent' => false,
				'validate'    => 'color',
				'output'      => array(
					'color' => '#cancel-comment-reply-link',
				),
			),
            array(
				'id'                => 'navein_blog_comment_meta_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Comment Meta Data', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-comment-date, .comment-edit-link' ),
			),
            array(
				'id'          => 'navein_blog_comment_meta_hover_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Comment Meta Data: Hover Color', 'navein' ),
				'default'     => '',
				'transparent' => false,
				'validate'    => 'color',
				'output'      => array(
					'color' => '.dtr-comment-date:hover, .comment-edit-link:hover',
				),
			),
            array(
				'id'    => 'navein_info_tags_settings',
				'type'  => 'info',
                'title' => esc_html__( 'Post Tags / Tagcloud Tags', 'navein' ),
			),
            array(
				'id'                => 'navein_tags_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Font', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
                'color'             => false,
				'output'            => array( '.wp-block-tag-cloud a, .dtr-meta-tags a' ),
			),
            array(
				'id'       => 'navein_tags_color',
				'type'     => 'link_color',
                'title'    => esc_html__( 'Color', 'navein' ),
                'active'   => false,
				'output'   => array( '.wp-block-tag-cloud a, .dtr-meta-tags a' ),
			),
			array(
				'id'          => 'navein_tags_bg_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Background Color', 'navein' ),
				'default'     => '',
				'transparent' => false,
				'validate'    => 'color',
				'output'      => array(
					'background-color' => '.wp-block-tag-cloud a, .dtr-meta-tags a',
				),
			),
			array(
				'id'          => 'navein_tags_hover_bg_color',
				'type'        => 'color',
				'title'       => esc_html__( 'On hover: Background Color', 'navein' ),
				'default'     => '',
				'transparent' => false,
				'validate'    => 'color',
				'output'      => array(
					'background-color' => '.wp-block-tag-cloud a:hover, .dtr-meta-tags a:hover',
				),
			),
			array(
				'id'          => 'navein_tags_border_color',
				'type'        => 'color',
				'title'       => esc_html__( 'Border Color', 'navein' ),
				'default'     => '',
				'transparent' => false,
				'validate'    => 'color',
				'output'      => array(
					'border-color' => '.wp-block-tag-cloud a, .dtr-meta-tags a',
				),
			),
			array(
				'id'          => 'navein_tags_hover_border_color',
				'type'        => 'color',
				'title'       => esc_html__( 'On hover: Border Color', 'navein' ),
				'default'     => '',
				'transparent' => false,
				'validate'    => 'color',
				'output'      => array(
					'border-color' => '.wp-block-tag-cloud a:hover, .dtr-meta-tags a:hover',
				),
			),
		),
	)
);