<?php
/**
 * Redux Settings
 *
 * @package NaveinTheme
 * @version 1.0.0
 */
// Exit if accessed directly
defined( 'ABSPATH' ) || exit;

Redux::set_section(
	$opt_name,
	array(
		'title'      => esc_html__( 'General Typography', 'navein' ),
		'id'         => 'navein_general_typography_settings',
        'icon'       => 'dashicons dashicons-arrow-right-alt',
		'subsection' => true,
		'fields'     => array(
            // body
            array(
				'id'    => 'navein_info_body_typo',
				'type'  => 'info',
                'title' => esc_html__( 'Body Typography', 'navein' ),
			),
            array(
				'id'                => 'navein_body_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Body Font', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => false,
                'line-height'       => false,
                'units'             => 'px',
				'output'            => array( 'body' ),
			),
            array(
				'id'       => 'navein_body_font_size',
				'type'     => 'text',
				'title'    => esc_html__( 'Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_body_line_height',
				'type'     => 'text',
				'title'    => esc_html__( 'Line Height', 'navein' ),
				'default'  => '',
			),

            // h1
            array(
				'id'    => 'navein_info_h1_typo',
				'type'  => 'info',
                'title' => esc_html__( 'H1 Typography', 'navein' ),
			),
            array(
				'id'                => 'navein_h1_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H1', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => false,
                'line-height'       => false,
                'units'             => 'px',
				'output'            => array( 'h1, .elementor-widget-heading h1.elementor-heading-title' ),
			),
            array(
				'id'       => 'navein_h1_font_size',
				'type'     => 'text',
				'title'    => esc_html__( 'Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h1_line_height',
				'type'     => 'text',
				'title'    => esc_html__( 'Line Height', 'navein' ),
				'default'  => '',
			),
            // h2
            array(
				'id'    => 'navein_info_h2_typo',
				'type'  => 'info',
                'title' => esc_html__( 'H2 Typography', 'navein' ),
			),
            array(
				'id'                => 'navein_h2_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H2', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => false,
                'line-height'       => false,
                'units'             => 'px',
				'output'            => array( 'h2, .elementor-widget-heading h2.elementor-heading-title' ),
			),
            array(
				'id'       => 'navein_h2_font_size',
				'type'     => 'text',
				'title'    => esc_html__( 'Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h2_line_height',
				'type'     => 'text',
				'title'    => esc_html__( 'Line Height', 'navein' ),
				'default'  => '',
			),
            // h3
            array(
				'id'    => 'navein_info_h3_typo',
				'type'  => 'info',
                'title' => esc_html__( 'H3 Typography', 'navein' ),
			),
            array(
				'id'                => 'navein_h3_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H3', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => false,
                'line-height'       => false,
                'units'             => 'px',
				'output'            => array( 'h3, .elementor-widget-heading h3.elementor-heading-title' ),
			),
            array(
				'id'       => 'navein_h3_font_size',
				'type'     => 'text',
				'title'    => esc_html__( 'Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h3_line_height',
				'type'     => 'text',
				'title'    => esc_html__( 'Line Height', 'navein' ),
				'default'  => '',
			),
            // h4
            array(
				'id'    => 'navein_info_h4_typo',
				'type'  => 'info',
                'title' => esc_html__( 'H4 Typography', 'navein' ),
			),
            array(
				'id'                => 'navein_h4_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H4', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => false,
                'line-height'       => false,
                'units'             => 'px',
				'output'            => array( 'h4, .elementor-widget-heading h4.elementor-heading-title' ),
			),
            array(
				'id'       => 'navein_h4_font_size',
				'type'     => 'text',
				'title'    => esc_html__( 'Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h4_line_height',
				'type'     => 'text',
				'title'    => esc_html__( 'Line Height', 'navein' ),
				'default'  => '',
			),
            // h5
            array(
				'id'    => 'navein_info_h5_typo',
				'type'  => 'info',
                'title' => esc_html__( 'H5 Typography', 'navein' ),
			),
            array(
				'id'                => 'navein_h5_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H5', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => false,
                'line-height'       => false,
                'units'             => 'px',
				'output'            => array( 'h5, .elementor-widget-heading h5.elementor-heading-title' ),
			),
            array(
				'id'       => 'navein_h5_font_size',
				'type'     => 'text',
				'title'    => esc_html__( 'Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h5_line_height',
				'type'     => 'text',
				'title'    => esc_html__( 'Line Height', 'navein' ),
				'default'  => '',
			),
            // h6
            array(
				'id'    => 'navein_info_h6_typo',
				'type'  => 'info',
                'title' => esc_html__( 'H6 Typography', 'navein' ),
			),
            array(
				'id'                => 'navein_h6_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H6', 'navein' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => false,
                'line-height'       => false,
                'units'             => 'px',
				'output'            => array( 'h6, .elementor-widget-heading h6.elementor-heading-title' ),
			),
            array(
				'id'       => 'navein_h6_font_size',
				'type'     => 'text',
				'title'    => esc_html__( 'Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h6_line_height',
				'type'     => 'text',
				'title'    => esc_html__( 'Line Height', 'navein' ),
				'default'  => '',
			),
            // info
            array(
				'id'    => 'navein_info_sm_headings',
				'type'  => 'info',
                'title' => esc_html__( 'Heading Sizes For Small Screens', 'navein' ),
				'desc'  =>  wp_kses( __('Set only if required', 'navein'), array( 'br' => array(), 'strong' => array(), ) ),
			),
            // h1
            array(
				'id'       => 'navein_h1_size_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H1 - Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h1_lh_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H1 - Line Height', 'navein' ),
				'default'  => '',
			),
            // h2
            array(
				'id'       => 'navein_h2_size_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H2 - Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h2_lh_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H2 - Line Height', 'navein' ),
				'default'  => '',
			),
            // h3
            array(
				'id'       => 'navein_h3_size_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H3 - Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h3_lh_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H3 - Line Height', 'navein' ),
				'default'  => '',
			),
            // h4
            array(
				'id'       => 'navein_h4_size_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H4 - Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h4_lh_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H4- Line Height', 'navein' ),
				'default'  => '',
			),
            // h5
            array(
				'id'       => 'navein_h5_size_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H5 - Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h5_lh_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H5 - Line Height', 'navein' ),
				'default'  => '',
			),
            // h6
             array(
				'id'       => 'navein_h6_size_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H6 - Font Size', 'navein' ),
				'subtitle' => esc_html__( 'Make sure to give unit like px,em,rem', 'navein' ),
				'desc'     => esc_html__( 'Example: 16px', 'navein' ),
				'default'  => '',
			),
            array(
				'id'       => 'navein_h6_lh_mobile',
				'type'     => 'text',
				'title'    => esc_html__( 'H6 - Line Height', 'navein' ),
				'default'  => '',
			),
		),
	)
);